### ISSUE TITLE
Layout calculation fails if each criterion has exactly one sub-criterion

### ISSUE THREAD

**Issue by netzwerg** [fhnw-saav/saav#29]
```
Caused by: java.lang.ArithmeticException: / by zero
	at ch.fhnw.ima.saav.model.layout$QualityLayout.<init>(layout.scala:35)
	at ch.fhnw.ima.saav.model.app$QualityModel$.apply(app.scala:76)
	at ch.fhnw.ima.saav.model.app$AppModel$.apply(app.scala:46)
```

**Comment by netzwerg** [comment]
Fixed
